# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d24bd70ecbdc183fbcd4207b491267168d45b176230adb6766916df7cee82e928474e51052a026af9c7a3855505f38bf494b8cb53a730506ef6eb46c47a5b6a9

test:
  secret_key_base: a3d028b6ede11e498aec80e032f5c2320bb1dc6759370b7217b9fa3517dd6cef9d3f8349fc0a71e7b214403f5d901d46ac82e29161d71ca2bf23218cdc066c78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
